#! /bin/sh

if [ "$#" -ne 2 ]; then
    echo "add-network VLAN IP/MASK"
    exit 1
fi

VLAN=$1
IP=$2

IFACE="gre-lr0"
ip link add link $IFACE name $IFACE.$VLAN type vlan id $VLAN
ip addr add $IP dev $IFACE.$VLAN
ip link set $IFACE.$VLAN up
