#! /bin/sh
#COUNT

#BOARD

if [ "$#" -eq 1 ]; then
    COUNT=$(($1*2+1))
    IPTUN="10.0.0.$COUNT/31"
else
    echo "start-stocat REMOTECOUNT [IP/MASK]"
    exit 1
fi

LOCALPORT="20000"
REMOTEPORT=$(($COUNT+10000-1))
echo $REMOTEPORT

TUNNAME="socat0"
WSURL="ws://212.189.207.205:8080"
echo $REMOTEPORT $IPTUN

socat -d -d TCP-L:$LOCALPORT,bind=localhost,reuseaddr,forever,interval=10 TUN:$IPTUN,tun-name=$TUNNAME,iff-up &
/opt/usr/lib/node_modules/wstun/bin/wstun.js -r $REMOTEPORT:localhost:$LOCALPORT $WSURL &

ifconfig $TUNNAME
while [ $? -ne 0 ];
do
sleep 3; ip link set $TUNNAME up;
done