#! /bin/sh
PORT="20000"
IFACE="socat0"

PID_SOCAT=$(ps www | grep TCP-L | grep $IFACE | awk '{print $1}')
PID_WSTUN=$(ps www | grep wstun | grep $PORT | awk '{print $1}')
kill -9 $PID_WSTUN $PID_SOCAT

