#!/bin/sh /etc/rc.common
# authors: 	https://github.com/artynet

#	
#	Ideino is based on Noide project by Dave Stone https://github.com/davidjamesstone/noide. 
#	Ideino https://github.com/ideino/ideino-linino-dist is released under the MIT License:
#	
#   Copyright (C) 2014 by Ideino
#
#
export PATH=/usr/bin:/bin:/sbin:/opt/usr/bin
export NODEJS=/opt/usr/bin/node
export LD_LIBRARY_PATH=/opt/usr/lib
export NPM=/opt/usr/bin/npm
export NODE_PATH=/usr/lib/node_modules:/opt/usr/lib/node_modules:$NODE_PATH

START=99

start () {
  
    if [ -x $NODEJS ] && [ -e /opt/node-lighthing-rod/s4t-wamp-client_yun.js ]
      
	then
	
	      $NODEJS --stack_size=1024 --max_old_space_size=20 --max_new_space_size=2048 --max_executable_size=5 \
		  --gc_global --gc_interval=100 /opt/node-lighthing-rod/s4t-wamp-client_yun.js & > /dev/null 2>&1
	  
      fi

}

stop () {

      kill -9 `ps www | grep s4t-wamp-client_yun | grep -v grep | awk {'print $1'}` > /dev/null 2>&1
      
}
