#!/bin/sh /etc/rc.common
#
#Apache License
#                           Version 2.0, January 2004
#                        http://www.apache.org/licenses/
#
#Copyright (c) 2014 2015 Andrea Rocco Lotronto
#

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/opt/usr/bin
export NODEJS=/opt/usr/bin/node
export LD_LIBRARY_PATH=/opt/usr/lib
export NPM=/opt/usr/bin/npm
export NODE_PATH=/usr/lib/node_modules:/opt/usr/lib/node_modules:$NODE_PATH

START=99
STOP=99
MYPID=`ps www | grep s4t-wamp-client_yun.js | grep -v grep | awk {'print $1'}`

boot () {

start
}
start () {
	if [ -r $MYPID ]; then
    	cd /opt/node-lighthing-rod
    	node s4t-wamp-client_yun.js > /opt/node-lighthing-rod/log &
    	echo "Service is started"
    else
    	echo "Service is already started with PID $MYPID"	
    fi

}
stop () {
      kill -9 `ps www | grep s4t-wamp-client_yun.js | grep -v grep | awk {'print $1'}` > /dev/null 2>&1
      
}
