#!/bin/sh /etc/rc.common
#
#              Apache License
#        Version 2.0, January 2004
#     http://www.apache.org/licenses/
#
#Copyright (c) 2014 2015 Andrea Rocco Lotronto


export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export NODEJS=/usr/bin/node
export LD_LIBRARY_PATH=/usr/lib
export NPM=/usr/bin/npm
export NODE_PATH=/usr/lib/node_modules:/usr/lib/node_modules:$NODE_PATH

START=99
STOP=99

boot () {

        start

}

start () {

        pid=`ps www | grep lightning-rod.js | grep -v grep | awk {'print $1'}`

        if [ -r $pid ]; then
                cd /usr/lib/node_modules/iotronic-lightning-rod
                node lightning-rod.js >> /dev/null & # /var/log/s4t-lightning-rod.log &
                echo "Lightning-rod is started"
        else
                echo "Lightning-rod is already started with PID $pid"
        fi

}

stop () {
        kill -9 `ps www | grep node | grep -v grep | awk {'print $1'}` > /dev/null 2>&1
        echo "Lightning-rod is stopped"
}

restart () {

        stop
        start

}
