#!/bin/sh /etc/rc.common
#
#              Apache License
#        Version 2.0, January 2004
#     http://www.apache.org/licenses/
#
#Copyright (c) 2017 Nicola Peditto


export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export NODEJS=/usr/bin/node
export LD_LIBRARY_PATH=/usr/lib
export NPM=/usr/bin/npm
export NODE_PATH=/usr/lib/node_modules:/usr/lib/node_modules:$NODE_PATH
export NODE_TLS_REJECT_UNAUTHORIZED=0
export IOTRONIC_HOME=/var/lib/iotronic
export LIGHTNINGROD_HOME=$NODE_PATH/@mdslab/iotronic-lightning-rod
export LIGHTNINGROD_REGEX='lightning-rod.js'
export WSTUN_REGEX='wstun.js'

START=99
STOP=99

boot () {

        start
        echo "LR booting..."
}

start () {

        pid=`pgrep -f "${LIGHTNINGROD_REGEX}"`

        if [ -r $pid ]; then
            if [ -e $LIGHTNINGROD_HOME/lightning-rod.js ]; then
                node $LIGHTNINGROD_HOME/lightning-rod.js >> /dev/null & # /var/log/iotronic/lightning-rod.log &
                echo "Lightning-rod has been started"
            else
                echo "Lightining-rod not installed"
            fi
        else
                echo "Lightning-rod is already started with PID $pid"
        fi

}

stop () {
        if pkill -9 -f "${WSTUN_REGEX}"; then
            echo "WSTUN processes have been stopped"
        else
            echo "WSTUN processes was already stopped"
        fi

        if pkill -9 -f "${LIGHTNINGROD_REGEX}"; then
            echo "Lightning-rod has been stopped"
        else
            echo "Lightning-rod was already stopped"
        fi
}

restart () {

        stop
        start

}
