#! /bin/sh
if [ "$#" -ne 2 ]; then
    echo "start-stocat REMOTEPORT IPTUN"
    return 1
fi

REMOTEPORT=$1
IPTUN=$2

LOCALPORT="20000"
#REMOTEPORT="5000"
#IPTUN="10.0.0.6/24"

TUNNAME="soc"$REMOTEPORT
WSURL="ws://212.189.207.205:8080"

set -o verbose

socat -d -d TCP-L:$LOCALPORT,bind=localhost,reuseaddr,forever,interval=10 TUN:$IPTUN,tun-type=tap,tun-name=$TUNNAME,iff-up &
/opt/usr/lib/node_modules/wstun/bin/wstun.js -r $REMOTEPORT:localhost:$LOCALPORT $WSURL &
#ifconfig $TUNNAME
#while [ $? -ne 0 ];
#do
#sleep 3; ip link set $TUNNAME up;
#done