#!/bin/sh

echo "Uninstalling..."
rm_check=
echo -n "Do you want to remove iotronic home (/var/lib/iotronic) ? (yes/no) "
read rm_check

if [ "$rm_check" = "yes" ]; then
	rm -rf /var/lib/iotronic/
else
	echo "--> iotronic home is save! "

fi
