#!/bin/sh       

echo "Installing..."
/usr/bin/npm install -g --unsafe https://github.com/PlayNetwork/node-statvfs/tarball/v3.0.0
echo "--> 3rd-party dependencies installed."

IOTRONIC_HOME="/var/lib/iotronic"

if [ -d "$IOTRONIC_HOME" ]; then

    rm_check=
    echo -n "Do you want to keep IoTronic home (/var/lib/iotronic) ? (yes/no) "
    read rm_check

    if [ "$rm_check" = "yes" ]; then

        echo "--> IoTronic home is save!"

    fi

fi

if [ "$rm_check" = "no" ] || [ ! -d "$IOTRONIC_HOME" ]; then

    mkdir /var/lib/iotronic/
    cd /var/lib/iotronic/ && mkdir plugins && mkdir drivers

    cp $NODE_PATH/@mdslab/iotronic-lightning-rod/settings.example.json /var/lib/iotronic/settings.json
    cp $NODE_PATH/@mdslab/iotronic-lightning-rod/modules/plugins-manager/plugins.example.json /var/lib/iotronic/plugins/plugins.json
    cp $NODE_PATH/@mdslab/iotronic-lightning-rod/modules/drivers-manager/drivers.example.json /var/lib/iotronic/drivers/drivers.json

    chmod +x $NODE_PATH/@mdslab/iotronic-lightning-rod/lr-server.js

    mkdir -p /var/log/iotronic/plugins
    touch /var/log/iotronic/lightning-rod.log

fi


echo "Configuring..."

# Set Environment variables
if grep -Fq "IOTRONIC_HOME" /etc/environment
then
    # if found
    echo "IOTRONIC_HOME env var already set."
else
    # if not found
    echo "Setting IOTRONIC_HOME env var."
    echo "IOTRONIC_HOME=/var/lib/iotronic" >> /etc/environment
    . /etc/environment
fi

if grep -Fq "LIGHTNINGROD_HOME" /etc/environment
then
    # if found
    echo "LIGHTNINGROD_HOME env var already set."
else
    # if not found
    echo "Setting LIGHTNINGROD_HOME env var."
    echo "LIGHTNINGROD_HOME=$NODE_PATH/@mdslab/iotronic-lightning-rod" >> /etc/environment
    . /etc/environment
fi


if grep -Fq "NODE_TLS_REJECT_UNAUTHORIZED" /etc/environment
then
    # if found
    echo "NODE_TLS_REJECT_UNAUTHORIZED env var already set."
else
    # if not found
    echo "Setting NODE_TLS_REJECT_UNAUTHORIZED env var."
    echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> /etc/environment
    . /etc/environment
fi

echo "After the installation execute lr_configure.sh script in order to complete the Lightning-rod configuration!"
echo "--> $NODE_PATH/@mdslab/iotronic-lightning-rod/scripts/lr_configure.sh"
chmod +x $NODE_PATH/@mdslab/iotronic-lightning-rod/scripts/lr_configure.sh

echo "Bye!"
